name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Welcome to my first workflow"

        - name: checkout action
          uses: actions/checkout@v4
        
        - name: Read file
          run: |
            ls -ltra
            chmod +x script.sh
            ./script.sh